In [1]:

import torch
torch.__version__

'2.13.0+cpu'

In [3]:
scalar = torch.tensor(3)
scalar

tensor(3)

In [4]:
scalar.item()

3

In [7]:
vector = torch.tensor([19,9.3])
vector

tensor([19.0000,  9.3000])

In [8]:
vector[0]

tensor(19.)

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [12]:
matrix = torch.tensor([[10,12],[23,33]])
matrix

tensor([[10, 12],
        [23, 33]])

In [13]:
matrix.ndim

2

In [14]:
matrix.shape

torch.Size([2, 2])

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor, random_tensor.ndim, random_tensor.shape, random_tensor.dtype

(tensor([[[0.4833, 0.9446, 0.2144, 0.4089],
          [0.6254, 0.3326, 0.2018, 0.8027],
          [0.5858, 0.1692, 0.7578, 0.5931]],
 
         [[0.0394, 0.0320, 0.9192, 0.2416],
          [0.0064, 0.7206, 0.4670, 0.0275],
          [0.7604, 0.4738, 0.9361, 0.1329]]]),
 3,
 torch.Size([2, 3, 4]),
 torch.float32)

In [20]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [22]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [23]:
# Use torch.arange(), torch.range() is deprecated 
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

/tmp/ipykernel_870167/193451495.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [26]:
torch.matmul(tensor_A, tensor_B.T) # (this will error)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [29]:
tensor_A@ tensor_B.T 

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [30]:
tensor_A*tensor_B

tensor([[ 7., 20.],
        [24., 44.],
        [45., 72.]])